branches:
  only:
    - master
    - dev

environment:
  global:
    # only do for Python >= 3.6.
    CIBW_SKIP: "cp27-* cp33-* cp34-* cp35-*"
    CIBW_BEFORE_BUILD: "python -m pip install -r requirements.txt"

    TWINE_USERNAME: mabucchi
    TWINE_PASSWORD:
      secure: ffBVdW93F+PhTrof4BvLYw==

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      APPVEYOR_JOB_NAME: "python37-x64-vs2015"

stack: python 3.7

init:
  - cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install: python -m pip install cibuildwheel==1.3.0

build_script: python -m cibuildwheel --output-dir dist

artifacts:
  - path: "dist\\*.whl"
    name: Wheels

for:
  - branches:
      only:
        - master
    deploy_script:
      - python -m pip install twine
      - "python -m twine upload --skip-existing dist\\*.whl"
