branches:
  only:
    - master
    - dev

environment:
  global:
    # only do for Python >= 3.6.
    CIBW_SKIP: "cp27-* cp33-* cp34-* cp35-*"
    CIBW_BEFORE_BUILD: "python -m pip install -r requirements.txt"

    TWINE_USERNAME: mabucchi
    TWINE_PASSWORD:
      secure: ffBVdW93F+PhTrof4BvLYw==

install:
  - python -m pip install cibuildwheel==0.10.1

build_script:
  - cibuildwheel --output-dir dist

artifacts:
  - path: "dist\\*.whl"
    name: Wheels

for:
  - branches:
      only:
        - master
    deploy_script:
      - python -m pip install twine
      - "python -m twine upload --skip-existing dist\\*.whl"
