env:
  global:
    # only do for Python >= 3.6.
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-* *-manylinux1_i686"
    - CIBW_BEFORE_BUILD="python -m pip install -r requirements.txt"
matrix:
  include:
    - language: python
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required
      python: "3.7"
      services:
        - docker
      install:
        - pip3 install --upgrade cibuildwheel
        - touch .cibuildwheel
    - os: osx
      language: generic
      install:
        - sudo pip2 install --upgrade cibuildwheel
        - touch .cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse