name: TestPyPI CI/CD

on:
  workflow_dispatch:

jobs:
  build_wheels:
    
    name: Build wheel for ${{matrix.python.cp}}-${{matrix.buildplat.sys}}-${{matrix.buildplat.arch}}
    runs-on: ${{ matrix.buildplat.runs_on }}
    
    strategy:
      matrix:
        buildplat:
          - { runs_on: ubuntu-latest, sys: manylinux, arch: x86_64, benv: "" }
          - { runs_on: macos-latest, sys: macosx, arch: arm64, benv: "14.0" }
          - { runs_on: windows-latest, sys: win, arch: AMD64, benv: "" }
        python:
          - { cp: "cp310",  rel: "3.10" }
          - { cp: "cp311",  rel: "3.11" }
          - { cp: "cp312",  rel: "3.12" }
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.rel }}$

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
  
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel cython>=3.0.1
          python -m pip install numpy
      
      - name: Build Wheels (MacOS)
        if: ${{ runner.os == 'macOS' }}
        env:
          CIBW_BUILD: ${{ matrix.python.cp }}-${{ matrix.buildplat.sys }}*
          CIBW_ARCHS: ${{ matrix.buildplat.arch }}
          # Setting CIBW_ENVIRONMENT overrides the environment settings in
          # pyproject.toml and would break the Windows build.  Ideally, we'd
          # set all of them there, but don't know how to pass "benv".
          CIBW_ENVIRONMENT: "MACOSX_DEPLOYMENT_TARGET=${{ matrix.buildplat.benv }}"
          AUTH_TOKEN: ${{ github.token }}
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python.cp }}-${{ matrix.buildplat.sys }}-${{ matrix.buildplat.arch }}
          path: ./wheelhouse/*

  build_sdist:
    name: Build source distribution
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  publis-to-testpypi:
    name: Publish package to TestPyPI
    needs:
      - build_wheels
      - build_sdist
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/
      - name: Publish in TestPyPI
        run: |
          python -m pip install twine
          python -m twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_ACCESS }}
