name: TestPyPI CI/CD

on:
  workflow_dispatch:

jobs:
  build_wheels:
    
    name: Build wheel on ${{ matrix.os }}-${{ matrix.python }}$
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        python: [3.10, 3.11, 3.12]    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}$

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
  
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel cython>=3.0.1
          python -m pip install numpy
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  publis-to-testpypi:
    name: Publish package to TestPyPI
    needs:
      - build_wheels
      - build_sdist
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/
      - name: Publish in TestPyPI
        run: |
          python -m pip install twine
          python -m twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_ACCESS }}
